# Generated by Django 4.2.1 on 2023-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('tools', models.ManyToManyField(blank=True, related_name='orderStore', to='store.tools', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'ЗаказНаМагазин',
                'verbose_name_plural': 'ЗаказНаМагазины',
                'ordering': ['-created_at'],
            },
        ),
    ]
