# Generated by Django 4.2.1 on 2023-05-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('order', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='store.orderstore', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'ПоставкаНаМагазин',
                'verbose_name_plural': 'ПоставкиНаМагазин',
                'ordering': ['-created_at'],
            },
        ),
    ]
