# Generated by Django 4.2.1 on 2023-05-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_deliverystore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDeliveryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('tools', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='store.tools', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'РучнаяПоставкаНаМагазин',
                'verbose_name_plural': 'РучныеПоставкиНаМагазин',
                'ordering': ['-created_at'],
            },
        ),
    ]
