# Generated by Django 4.2.1 on 2023-05-28 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_manualdeliverystore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverystore',
            options={'ordering': ['-created_at'], 'verbose_name': 'поставка на магазин', 'verbose_name_plural': 'поставки на магазин'},
        ),
        migrations.AlterModelOptions(
            name='manualdeliverystore',
            options={'ordering': ['-created_at'], 'verbose_name': 'ручная поставка на магазин', 'verbose_name_plural': 'ручные поставки на магазин'},
        ),
        migrations.AlterModelOptions(
            name='orderstore',
            options={'ordering': ['-created_at'], 'verbose_name': 'заказ на магазин', 'verbose_name_plural': 'заказы на магазин'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('delivery', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='store.deliverystore', verbose_name='Заказ')),
                ('manual_delivery', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='store.manualdeliverystore', verbose_name='ручной заказ')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
    ]
