# Generated by Django 4.2.1 on 2023-05-30 10:01

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_delivery_alter_product_manual_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='store.tag', verbose_name='Тег'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='Родительский класс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tools',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='store.category', verbose_name='Категория'),
        ),
    ]
