# Generated by Django 4.2.1 on 2023-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_tools_tag_category_tools_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='desc',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание'),
        ),
    ]
