# Generated by Django 4.2.1 on 2023-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_collectionproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionproducts',
            options={'ordering': ['created_at'], 'verbose_name': 'Добавленный товар в магазин.', 'verbose_name_plural': 'Добавленные товары в магазин.'},
        ),
        migrations.AddField(
            model_name='product',
            name='icode',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='внутренний код'),
        ),
        migrations.AlterField(
            model_name='collectionproducts',
            name='note',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Примечание'),
        ),
    ]
