# Generated by Django 4.2.1 on 2023-06-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_collectionproducts_options_product_icode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('code_record', models.TextField(blank=True, max_length=250, null=True, verbose_name='код записи')),
                ('price', models.FloatField(blank=True, verbose_name='Цена продажи')),
                ('note', models.TextField(blank=True, max_length=250, null=True, verbose_name='Примечание')),
                ('products', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['created_at'],
            },
        ),
    ]
